<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{
    public function getDriversByTransport($transportId) {
       $em = $this->getEntityManager();

       $dql = "SELECT d FROM MainBundle:Driver d JOIN d.transport t WHERE t.id = ?1";
       return $em->createQuery($dql)->setParameter(1, $transportId)->getResult();
   }
}
