<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends EntityRepository
{
    public function remove(Transport $t){
        $t->setActive(false);
}
}
