# app/config/security.yml -FosUserBundle
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPERATOR:    ROLE_USER
        ROLE_SUPERVISOR:  ROLE_OPERATOR
        ROLE_ADMIN:       ROLE_SUPERVISOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/tank/show/$, role: ROLE_OPERATOR }
        - { path: ^/inventory/index/show/$, role: ROLE_OPERATOR }
        - { path: ^/inventory/ajax/list, role: ROLE_OPERATOR }
        - { path: ^/provider, role: ROLE_SUPERVISOR }
        - { path: ^/client, role: ROLE_SUPERVISOR }
        - { path: ^/transport, role: ROLE_SUPERVISOR }
        - { path: ^/driver, role: ROLE_SUPERVISOR }
        - { path: ^/product, role: ROLE_SUPERVISOR }
        - { path: ^/tank, role: ROLE_SUPERVISOR }
        - { path: ^/inventory, role: ROLE_SUPERVISOR }
        - { path: ^/ingress, role: ROLE_SUPERVISOR }
        - { path: ^/egress, role: ROLE_SUPERVISOR }
        - { path: ^/pass, role: ROLE_SUPERVISOR }
        - { path: ^/report/inventory/index, role: ROLE_SUPERVISOR }
        - { path: ^/group, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN }
