# app/config/security.yml -FosUserBundle
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPERATOR:    ROLE_USER
        ROLE_SUPERVISOR:  ROLE_OPERATOR
        ROLE_ADMIN:       ROLE_SUPERVISOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/tank/$, role: ROLE_OPERATOR }
        - { path: ^/tank/new$, role: ROLE_SUPERVISOR }
        - { path: ^/tank/create$, role: ROLE_SUPERVISOR }
        - { path: ^/tank/[0-9]+/show$, role: ROLE_OPERATOR }
        - { path: ^/tank/[0-9]+/edit$, role: ROLE_SUPERVISOR }
        - { path: ^/tank/[0-9]+/update$, role: ROLE_SUPERVISOR }
        - { path: ^/tank/[0-9]+/delete$, role: ROLE_SUPERVISOR }
        - { path: ^/tank/[0-9]+/getbytank$, role: ROLE_OPERATOR }
        - { path: ^/tank/[0-9]+/calculateCapacity$, role: ROLE_OPERATOR }
        - { path: ^/inventory/index/[0-9]+$, role: ROLE_OPERATOR }
        - { path: ^/inventory/ajax/list$, role: ROLE_OPERATOR }
        - { path: ^/inventory/[0-9]+/new$, role: ROLE_OPERATOR }
        - { path: ^/inventory/create$, role: ROLE_OPERATOR }
        - { path: ^/inventory/[0-9]+/show$, role: ROLE_OPERATOR }
        - { path: ^/inventory/[0-9]+/edit$, role: ROLE_SUPERVISOR }
        - { path: ^/inventory/[0-9]+/update$, role: ROLE_SUPERVISOR }
        - { path: ^/inventory/[0-9]+/delete$, role: ROLE_SUPERVISOR }
        - { path: ^/ingress/$, role: ROLE_OPERATOR }
        - { path: ^/ingress/list$, role: ROLE_OPERATOR }
        - { path: ^/ingress/[0-9]+/show$, role: ROLE_OPERATOR }
        - { path: ^/ingress/new$, role: ROLE_OPERATOR }
        - { path: ^/ingress/create$, role: ROLE_OPERATOR }
        - { path: ^/ingress/[0-9]+/edit$, role: ROLE_SUPERVISOR }
        - { path: ^/ingress/[0-9]+/update$, role: ROLE_SUPERVISOR }
        - { path: ^/ingress/[0-9]+/delete$, role: ROLE_SUPERVISOR }
        - { path: ^/ingress/[0-9]+/export$, role: ROLE_OPERATOR }
        - { path: ^/ingress/[0-9]+/newDownload$, role: ROLE_OPERATOR }
        - { path: ^/ingress/creatDownload$, role: ROLE_OPERATOR }
        - { path: ^/egress/$, role: ROLE_OPERATOR }
        - { path: ^/egress/list$, role: ROLE_OPERATOR }
        - { path: ^/egress/[0-9]+/show$, role: ROLE_OPERATOR }
        - { path: ^/egress/new$, role: ROLE_OPERATOR }
        - { path: ^/egress/create$, role: ROLE_OPERATOR }
        - { path: ^/egress/[0-9]+/edit$, role: ROLE_SUPERVISOR }
        - { path: ^/egress/[0-9]+/update$, role: ROLE_SUPERVISOR }
        - { path: ^/egress/[0-9]+/delete$, role: ROLE_SUPERVISOR }
        - { path: ^/egress/[0-9]+/export$, role: ROLE_OPERATOR }
        - { path: ^/pass/$, role: ROLE_OPERATOR }
        - { path: ^/pass/ajax/list$, role: ROLE_OPERATOR }
        - { path: ^/pass/[0-9]+/show$, role: ROLE_OPERATOR }
        - { path: ^/pass/new$, role: ROLE_OPERATOR }
        - { path: ^/pass/create$, role: ROLE_OPERATOR }
        - { path: ^/pass/[0-9]+/edit$, role: ROLE_SUPERVISOR }
        - { path: ^/pass/[0-9]+/update$, role: ROLE_SUPERVISOR }
        - { path: ^/pass/[0-9]+/delete$, role: ROLE_SUPERVISOR }
        - { path: ^/pass/[0-9]+/checkdatetime, role: ROLE_OPERATOR }
        - { path: ^/product/[0-9]+/getbyproduct, role: ROLE_OPERATOR }
        - { path: ^/driver/[0-9]+/getbytransport, role: ROLE_OPERATOR }
        - { path: ^/provider, role: ROLE_SUPERVISOR }
        - { path: ^/client, role: ROLE_SUPERVISOR }
        - { path: ^/transport, role: ROLE_SUPERVISOR }
        - { path: ^/driver, role: ROLE_SUPERVISOR }
        - { path: ^/product, role: ROLE_SUPERVISOR }
        - { path: ^/report/inventory/index, role: ROLE_SUPERVISOR }
        - { path: ^/report/inventory/export, role: ROLE_SUPERVISOR }
        - { path: ^/report/tank/index, role: ROLE_SUPERVISOR }
        - { path: ^/report/tank/export, role: ROLE_SUPERVISOR }
        - { path: ^/group, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN }
