ingress:
    path:     /
    defaults: { _controller: "MainBundle:Ingress:index" }

ingress_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Ingress:show" }
    options:
        expose: true

ingress_new:
    path:     /new
    defaults: { _controller: "MainBundle:Ingress:new" }

ingress_create:
    path:     /create
    defaults: { _controller: "MainBundle:Ingress:create" }
    methods:  POST

ingress_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Ingress:edit" }
    options:
        expose: true

ingress_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Ingress:update" }
    methods:  [POST, PUT]

ingress_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Ingress:delete" }
    methods:  [POST, DELETE]

ingress_export:
    path:     /{type}/export
    defaults: { _controller: "MainBundle:Ingress:export" }
    
ingress_list:
    path:     /list
    defaults: { _controller: "MainBundle:Ingress:listAjax" }
    
ingress_newDownload:
    path:     /{id}/newDownlaod
    defaults: { _controller: "MainBundle:Ingress:downloadNew" }
    options:
        expose: true

ingress_createDownload:
    path:     /createDownload
    defaults: { _controller: "MainBundle:Ingress:downloadCreate" }
    methods:  POST