inventory:
    path:     /{id}/
    defaults: { _controller: "MainBundle:Inventory:index" }

inventory_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Inventory:show" }

inventory_new:
    path:     /new
    defaults: { _controller: "MainBundle:Inventory:new" }

inventory_create:
    path:     /create
    defaults: { _controller: "MainBundle:Inventory:create" }
    methods:  POST

inventory_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Inventory:edit" }

inventory_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Inventory:update" }
    methods:  [POST, PUT]

inventory_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Inventory:delete" }
    methods:  [POST, DELETE]
