pass:
    path:     /
    defaults: { _controller: "MainBundle:Pass:index" }
    
pass_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Pass:show" }
    options:
        expose: true

pass_new:
    path:     /new
    defaults: { _controller: "MainBundle:Pass:new" }

pass_create:
    path:     /create
    defaults: { _controller: "MainBundle:Pass:create" }
    methods:  POST
    
pass_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Pass:edit" }
    options:
        expose: true

pass_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Pass:update" }
    methods:  [POST, PUT]

pass_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Pass:delete" }
    methods:  [POST, DELETE]
    
pass_ajax_list:
    path:     /ajax/list
    defaults: { _controller: "MainBundle:Pass:listAjax" }
    
checkDateTime:
    pattern: /{date}/checkdatetime
    defaults: { _controller: "MainBundle:Pass:checkDateTimeAjax" }
    options:
        expose: true
