provider:
    path:     /
    defaults: { _controller: "MainBundle:Provider:index" }

provider_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Provider:show" }

provider_new:
    path:     /new
    defaults: { _controller: "MainBundle:Provider:new" }

provider_create:
    path:     /create
    defaults: { _controller: "MainBundle:Provider:create" }
    methods:  POST

provider_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Provider:edit" }

provider_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Provider:update" }
    methods:  [POST, PUT]

provider_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Provider:delete" }
    methods:  [POST, DELETE]
