report_inventory_index:
    path:     /inventory/index
    defaults: { _controller: "MainBundle:Report:inventoryIndex" }

report_inventory_ajax_list:
    path:     /inventory/list
    defaults: { _controller: "MainBundle:Report:inventoryAjaxList" }

report_inventory_export:
    path:     /inventory/export
    defaults: { _controller: "MainBundle:Report:inventoryExport" }

report_tank_index:
    path:     /tank/index
    defaults: { _controller: "MainBundle:Report:tankIndex" }
    
report_tank_ajax_list:
    path:     /tank/list
    defaults: { _controller: "MainBundle:Report:tankAjaxList" }
    
report_tank_export:
    path:     /tank/export
    defaults: { _controller: "MainBundle:Report:tankExport" }