transport:
    path:     /
    defaults: { _controller: "MainBundle:Transport:index" }

transport_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Transport:show" }

transport_new:
    path:     /new
    defaults: { _controller: "MainBundle:Transport:new" }

transport_create:
    path:     /create
    defaults: { _controller: "MainBundle:Transport:create" }
    methods:  POST

transport_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Transport:edit" }

transport_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Transport:update" }
    methods:  [POST, PUT]

transport_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Transport:delete" }
    methods:  [POST, DELETE]
